stages:
  - build
  - release

variables:
  APP_NAME: "ZWOCameraBridge"

build:
  stage: build
  tags:
    - macos
  script:
    - curl -L https://github.com/openframeworks/openFrameworks/releases/download/0.12.0/of_v0.12.0_osx_release.zip -o of.zip
    - unzip -q of.zip
    - mv of_v0.12.0_osx_release ..
    - ./build.sh Release
    - cd bin
    - hdiutil create -volname "$APP_NAME" -srcfolder "$APP_NAME.app" -ov -format UDZO "$APP_NAME.dmg"
  artifacts:
    paths:
      - bin/${APP_NAME}.dmg

release:
  stage: release
  dependencies:
    - build
  script:
    - echo "Release created"
  release:
    name: "$CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG"
    assets:
      links:
        - name: "${APP_NAME}.dmg"
          url: "${CI_PROJECT_URL}/-/jobs/$CI_JOB_ID/artifacts/file/bin/${APP_NAME}.dmg"
  only:
    - tags
